### PR TITLE
travis, removes mentions of travis

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by gnott** [comment]
If I could find the badge generated by Jenkins to replace the travis-ci one, would that be an acceptable addition?

**Comment by lsh-0** [comment]
Absolutely

**Comment by gnott** [comment]
Hmm, since this one doesn't appear in the list of libraries, and it only builds pull requests, that badge might not be available for this one. It's not a requirement for all, only maybe if there's already an existing badge to use as a substitute.

**Review by gnott — APPROVED** [review]

**Comment by lsh-0** [comment]
Not sure how it works, but you can always add one later. Merging.

**Pull request merged**
